name: VipSystem
version: '${project.version}'
main: me.zhanshi123.vipsystem.Main
depend: [Vault]
softdepend: [PlaceholderAPI]
authors: [Soldier]
description: A plugin to manage Vip automatically
website: https://dl.zhanshi123.me#VipSystem
api-version: 1.16
commands:
  vipsys:
    description: Main command of VipSystem
    aliases:
      - vip
    usage: Plugin initializing failed, please check the log
permissions:
  vipsystem.changevip:
    description: Allows to use changevip Command
    default: true
  vipsystem.give:
    description: Allows to use give Command
    default: op
  vipsystem.remove:
    description: Allows to use remove Command
    default: op
  vipsystem.reload:
    description: Allows to use remove Command
    default: op